# Generated by Django 3.0.7 on 2020-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200814_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('제품준비중', '제품준비중'), ('배송중', '배송중'), ('배송완료', '배송완료')], max_length=200, null=True),
        ),
    ]
